services:
      
  depensioDB:
    image: postgres:15

  depensio.api:
    image: ${DOCKER_REGISTRY-}depensioapi
    build:
      context: .
      dockerfile: backend/depensio.Api/Dockerfile

  depensio.web:
    image: ${DOCKER_REGISTRY-}depensioweb
    build:
      context: .
      dockerfile: frontend/depensio.Web/Dockerfile

volumes:
  pgdata_depensio:




