services:
  depensioVault:
    container_name: depensioVault
    ports:
      - "8201:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root-token
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8201"
    volumes:
      - ./vault/policies:/vault/policies:ro
      - ./vault/shared:/vault/shared
    cap_add:
      - IPC_LOCK
    command: /bin/sh -c "
      vault server -dev -dev-root-token-id=root-token &
      sleep 2 &&
      /vault/policies/setup.sh &&
      wait"
    entrypoint: /vault/policies/setup.sh
    
  depensioDB:
    container_name: depensioDB
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: depensioDB
      MYSQL_USER: testRoot
      MYSQL_PASSWORD: 1234
    restart: always
    ports:
      - "3336:3306"
    volumes:
      - mysql_depensio:/var/lib/mysql

  # ef-migrator:
  #   container_name: ef-migrator
  #   depends_on:
  #     - depensioVault
  #     - depensioDB
  #   image: mcr.microsoft.com/dotnet/sdk:8.0
  #   volumes:
  #     - .:/src
  #     - ./vault/shared:/vault/shared
  #   working_dir: /src
  #   env_file:
  #     - ./vault/shared/vault-env.export
  #   environment:
  #     - ConnectionStrings__Database=DataBase
  #     - Vault__Uri=http://depensioVault:8200
  #   entrypoint: >
  #     sh -c '
  #       export PATH="/root/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin" &&
  #       dotnet tool install --global dotnet-ef &&
  #       dotnet ef migrations add InitialCreate --project backend/depensio.Infrastructure --startup-project backend/depensio.Api --output-dir Data/Migration'
                

  depensio.api:
    depends_on:
      - depensioVault
      - depensioDB
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=DataBase
      - Vault__Uri=http://depensioVault:8201
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./vault/shared:/vault/shared
    env_file:
      - ./vault/shared/vault-env.export


  depensio.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
