services:          
  depensioDB:
    container_name: depensioDB
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - pgdata_depensio:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1;' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - vault-net

  depensio.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ApiSettings__Uri=https://depensio.api:9102
      - JWT__ValidAudience=depensio.web
      - JWT__ValidIssuer=depensio.client
      - JWT__Secret=SuperSecureKeyThatMatchesClientAndServer
    restart: always
    ports:
      - "9001:8080"
      - "9002:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      depensio.api:
        condition: service_started
    networks:
      - vault-net

  depensio.api:
    depends_on:
      depensioDB:
        condition: service_healthy
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081      
      - ConnectionStrings__Database=${CONNECTION_STRING_API}
      - Vault__Path=${VAULT_PATH}
      - MailConfig__FromMailId=${MAIL_CONFIG_ID}
      - MailConfig__FromMailIdPassword=${MAIL_CONFIG_PASSWORD}
      - MailConfig__FromMailName=${MAIL_CONFIG_NAME}
      - MailConfig__Host=${MAIL_CONFIG_HOST}
      - MailConfig__Ports=${MAIL_CONFIG_PORT}
      - JWT__ValidAudience=${JWT_VALID_AUDIENCE}
      - JWT__ValidIssuer=${JWT_VALID_ISSUER}
      - JWT__Secret=${JWT_SECRET}
    ports:
      - "9101:8080"
      - "9102:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./vault/shared:/app/vault/shared
    networks:
      - vault-net

      
networks:
  vault-net:
    external: true 

