services:
  depensioDB:
    image: postgres:15
    container_name: depensioDB
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - pgdata_depensio:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1;' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    env_file:
      - ./.env
    networks:
      - vault-net
    
  ef-migrator:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: ef-migrator
    depends_on:
      depensioDB:
        condition: service_healthy
    volumes:
      - ./vault/shared:/app/vault/shared
      - .:/src
    working_dir: /src
    env_file:
      - ./.env
    entrypoint: sh -c "
      echo '? Attente des secrets Vault...' &&
      until [ -f ${VAULT_PATH} ]; do sleep 1; done &&
      dotnet tool install --global dotnet-ef &&
      export PATH=$PATH:/root/.dotnet/tools &&  
      export JWT__Secret=${JWT_SECRET_API} &&
      export ConnectionStrings__DataBase=${CONNECTION_STRING_API} &&
      export MailConfig__FromMailIdPassword=${MAIL_CONFIG_PASSWORD} &&
      export Vault__Path=${VAULT_PATH} &&
      dotnet ef database update --project backend/depensio.Infrastructure --startup-project backend/depensio.Api"
    networks:
      - vault-net

  depensio.web:
    image: ${DOCKER_REGISTRY-}depensioweb
    restart: always
    build:
      context: .
      dockerfile: frontend/depensio.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ApiSettings__Uri=${API_SETTINGS_URL}
      - JWT__ValidAudience=${JWT_VALID_AUDIENCE_WEB}
      - JWT__ValidIssuer=${JWT_VALID_ISSUER_WEB}
      - JWT__Secret=${JWT_SECRET_WEB}
    ports:
      - "9001:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      depensio.api:
        condition: service_started
    env_file:
      - ./.env
    networks:
      - vault-net

  depensio.api:
    image: ${DOCKER_REGISTRY-}depensioapi
    restart: always
    build:
      context: .
      dockerfile: backend/depensio.Api/Dockerfile
    depends_on:
      ef-migrator:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Poduction
      - ASPNETCORE_HTTP_PORTS=8080     
      - ConnectionStrings__DataBase=${CONNECTION_STRING_API}
      - Vault__Path=${VAULT_PATH}
      - MailConfig__FromMailId=${MAIL_CONFIG_ID}
      - MailConfig__FromMailIdPassword=${MAIL_CONFIG_PASSWORD}
      - MailConfig__FromMailName=${MAIL_CONFIG_NAME}
      - MailConfig__Host=${MAIL_CONFIG_HOST}
      - MailConfig__Ports=${MAIL_CONFIG_PORT}
      - JWT__ValidAudience=${JWT_VALID_AUDIENCE_API}
      - JWT__ValidIssuer=${JWT_VALID_ISSUER_API}
      - JWT__Secret=${JWT_SECRET_API}
      - N8N__Uri=${N8N_URI}
      - Email__Support=${EMAIL_SUPPORT}
      - WebhookId=${WEBHOOKID}
    ports:
      - "9101:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./vault/shared:/app/vault/shared
    env_file:
      - ./.env
    networks:
      - vault-net

      
networks:
  vault-net:
    external: true 
      
volumes:
  pgdata_depensio: