services:
  depensioVault:
    image: hashicorp/vault:1.13.3
    restart: always
    container_name: depensioVault
    ports:
      - "8201:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root-token
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8201"
    volumes:
      - ./vault/policies:/vault/policies:ro
      - ./vault/shared:/vault/shared
    cap_add:
      - IPC_LOCK
    entrypoint: /vault/policies/setup.deploy.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8201/v1/sys/health"]
      interval: 5s
      timeout: 3s
      retries: 20
    
  depensioDB:
    image: postgres:15
    container_name: depensioDB
    restart: always
    environment:
      POSTGRES_DB: depensioDB
      POSTGRES_USER: testRoot
      POSTGRES_PASSWORD: 1234
    ports:
      - "5436:5432"
    volumes:
      - pgdata_depensio:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "testRoot"]
      interval: 30s
      timeout: 15s
      retries: 10
            
  depensio.web:
    image: ${DOCKER_REGISTRY-}depensioweb
    restart: always
    build:
      context: .
      dockerfile: frontend/depensio.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ApiSettings__Uri=http://depensio.api:9101
    ports:
      - "9001:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      depensio.api:
        condition: service_started

  depensio.api:
    image: ${DOCKER_REGISTRY-}depensioapi
    restart: always
    build:
      context: .
      dockerfile: backend/depensio.Api/Dockerfile
    depends_on:
      depensioVault:
        condition: service_healthy
      depensioDB:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Poduction
      - ASPNETCORE_HTTP_PORTS=8080   
      - ConnectionStrings__Database=DataBase
      - Vault__Uri=http://depensioVault:8201
      - MailConfig__FromMailId=noreplytest@depensio.com
      - MailConfig__FromMailIdPassword=FromMailIdPassword
      - MailConfig__FromMailName=depensio
      - MailConfig__Host=mail.depensio.com
      - MailConfig__Ports=25
      - JWT__ValidAudience=User
      - JWT__ValidIssuer=http://localhost:9001
      - JWT__Secret=Secret
    ports:
      - "9101:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./vault/shared:/app/vault/shared:ro
      
volumes:
  pgdata_depensio: