services:
  depensioDB:
    image: postgres:15
    container_name: depensioDB
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - pgdata_depensio:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$$POSTGRES_PASSWORD psql -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1;' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - vault-net
    
  ef-migrator:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: ef-migrator
    depends_on:
      depensioDB:
        condition: service_healthy
    volumes:
      - ./vault/shared:/app/vault/shared
      - .:/src
    working_dir: /src
    entrypoint: sh -c "
      echo '? Attente des secrets Vault...' &&
      until [ -f /app/vault/shared/vault-depensio-env.json ]; do sleep 1; done &&
      dotnet tool install --global dotnet-ef &&
      export PATH=$PATH:/root/.dotnet/tools &&
      dotnet ef database update --project backend/depensio.Infrastructure --startup-project backend/depensio.Api"
    networks:
      - vault-net

  depensio.web:
    image: ${DOCKER_REGISTRY-}depensioweb
    restart: always
    build:
      context: .
      dockerfile: frontend/depensio.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ApiSettings__Uri=https://apidemo.depensio.com
      - JWT__ValidAudience=depensio.web
      - JWT__ValidIssuer=depensio.client
      - JWT__Secret=SuperSecureKeyThatMatchesClientAndServer
    ports:
      - "9001:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      depensio.api:
        condition: service_started
    networks:
      - vault-net

  depensio.api:
    image: ${DOCKER_REGISTRY-}depensioapi
    restart: always
    build:
      context: .
      dockerfile: backend/depensio.Api/Dockerfile
    depends_on:
      ef-migrator:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Poduction
      - ASPNETCORE_HTTP_PORTS=8080   
      - ConnectionStrings__Database=DataBase
      - Vault__Path=${VAULT_PATH}
      - MailConfig__FromMailId=noreplytest@depensio.com
      - MailConfig__FromMailIdPassword=FromMailIdPassword
      - MailConfig__FromMailName=depensio
      - MailConfig__Host=mail.depensio.com
      - MailConfig__Ports=25
      - JWT__ValidAudience=User
      - JWT__ValidIssuer=https://demo.depensio.com
      - JWT__Secret=Secret
    ports:
      - "9101:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./vault/shared:/app/vault/shared
    networks:
      - vault-net

      
networks:
  vault-net:
    external: true 
      
volumes:
  pgdata_depensio: